spring:
  profiles:
    active: sharding
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jas.sjdemo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
