dubbo:
  application:
    name: springboot-dubbo-demo # \u5F53\u524D\u670D\u52A1\u540D
  registry:
    protocol: zookeeper         # \u6CE8\u518C\u4E2D\u5FC3
    address: 127.0.0.1:2181     # \u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
  monitor:
    protocol: registry    